language: node_js
node_js:
  - "8.9.1"
install:
  - npm install
script:
  - npm run lint
  - npm run compile
before_deploy:
  - rm .gitignore
  - rm -fr lib && cp -r build/* . && rm -fr build
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
